source 'https://rubygems.org'


gem 'rails', '4.2.5'

gem 'rails-api'

gem 'spring', :group => :development


gem 'sqlite3'

# gem 'minitest', :group => :test

gem 'tests_doc', path: '../../../tests_doc', :group => :test

group :test, :development do
  gem 'byebug'
  gem 'rspec-rails', '~> 2.14'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
